### PR TITLE
Fix MissingReferenceException

### PR DESCRIPTION
**Pull request by Kuniwak**
An interactive component that held by TouchAndHold can get destroyed ~after delayMilis elappsed~ **during delayMilis**. Then TouchAndHold throw the following error:

> MissingReferenceException: The object of type 'Button' has been
> destroyed but you are still trying to access it. Your script should
> either check if it is null or you should not destroy the object.

This patch introduce null-check after delayMilis elappsed.

### CODE REVIEW

**Review by nowsprinting — COMMENTED** [review]
@Kuniwak san, Thank you for your PR!

At first, I want to understand an issue correctly.

I wrote the following reproduction test. However, the exception did not occur.

```
[Test]
public async Task TouchAndHold_DestroyTargetObjectDuringHold_UpIsNotCalled()
{
    var target = InteractiveComponentCollector.FindInteractiveComponents(false)
        .First(x => x.gameObject.name == "UsingOnPointerDownUpHandler");
    Assume.That(target.CanTouchAndHold(), Is.True);

    target.TouchAndHold(); // Not await
    await UniTask.Delay(200);

    Object.DestroyImmediate(target.gameObject); // Destroy target object during hold
    await UniTask.Delay(1000); // Wait for TouchAndHold task end
}
```

This code does not call `OnPointerUp`. However, also does not occur a `MissingReferenceException`.

At exiting `Task.Delay`, `OnPointerUp` is not called because `upHandler` is already destroyed.
(at TouchAndHoldOperator.cs line 48)

I confirmed this behavior in Unity 2019.4.40f1, 2022.3.11f1, and 2023.1.13f1.

**Comment by Kuniwak** [comment]
Hmm, seems strange. I confirmed that the exception had not been ocurred after applying this patch. I'm gonna try add a reproducing test.

**Comment by Kuniwak** [comment]
@nowsprinting I fixed the issue description and added the reproducing test at [2b3c339](https://github.com/nowsprinting/test-helper.monkey/pull/40/commits/2b3c339faf931ad86721f071df92716a2cdcc822).

**Comment by Kuniwak** [comment]
Sorry, I fix the coding-style problem after [the comment](https://github.com/nowsprinting/test-helper.monkey/pull/40#issuecomment-1776175268).

**Review by nowsprinting — APPROVED** [review]
Thanks, I confirmed the reproduction and fix!

**Pull request merged**
