### PR TITLE
Cut out RunStep from Run

### PR DESCRIPTION
**Pull request by Kuniwak**
Hi, I want only a part of `Run` to branch by a condition in `Run()` as following:

```csharp
public static async UniTask Run(MonkeyConfig config, CancellationToken cancellationToken = default)
{
    var endTime = config.Lifetime == TimeSpan.MaxValue
        ? TimeSpan.MaxValue.TotalSeconds
        : config.Lifetime.Add(TimeSpan.FromSeconds(Time.time)).TotalSeconds;

    config.Logger.Log($"Using {config.Random}");
    var lastOperationTime = Time.time;

    while (Time.time < endTime)
    {
        if (SomeConditionSatisifed) // added
        {                           // added
            DoSomething();          // added
        }                           // added
        else                        // added
        {                           // added
            var didAct = await RunStep(config, cancellationToken);
            if (didAct)
            {
                lastOperationTime = Time.time;
            }
            else if (config.SecondsToErrorForNoInteractiveComponent > 0)
            {
                Assert.IsTrue(
                    (Time.time - lastOperationTime) < config.SecondsToErrorForNoInteractiveComponent,
                    $"Interactive component not found in {config.SecondsToErrorForNoInteractiveComponent} seconds"
                );
            }

            await UniTask.Delay(config.DelayMillis, DelayType.DeltaTime, cancellationToken: cancellationToken);
        }
    }
}
```

So, I cut out the part into a new public method `RunStep` from `Run`.

### CODE REVIEW

**Review by nowsprinting — APPROVED** [review]
LGTM! as a refactoring.
(I don't understand its use case yet...)

**Comment by Kuniwak** [comment]
I can implement what I want by making uGUIMonkeyAgent life very short, but it may lead to get lower coverage per a period. So I needed a more faster way.

**Comment by nowsprinting** [comment]
@Kuniwak san,
If you need more faster, let me know.
I can add an option using the `Selectable.allSelectablesArray()` method. This works fast only for UI elements on Canvas.

**Comment by Kuniwak** [comment]
@nowsprinting I think it is useful, but it might be a way that not enough to get higher coverage per a period. I'm gonna tell you about the option needs if I need it.

**Pull request merged**
